# TX / RX
set_property PACKAGE_PIN V2 [get_ports {rxp[0]}]
set_property PACKAGE_PIN V1 [get_ports {rxn[0]}]
set_property PACKAGE_PIN W4 [get_ports {txp[0]}]
set_property PACKAGE_PIN W3 [get_ports {txn[0]}]
set_property PACKAGE_PIN T2 [get_ports {rxp[1]}]
set_property PACKAGE_PIN T1 [get_ports {rxn[1]}]
set_property PACKAGE_PIN U4 [get_ports {txp[1]}]
set_property PACKAGE_PIN U3 [get_ports {txn[1]}]
set_property PACKAGE_PIN P2 [get_ports {rxp[2]}]
set_property PACKAGE_PIN P1 [get_ports {rxn[2]}]
set_property PACKAGE_PIN R4 [get_ports {txp[2]}]
set_property PACKAGE_PIN R3 [get_ports {txn[2]}]

set_property PACKAGE_PIN M2 [get_ports {rxp[3]}]
set_property PACKAGE_PIN M1 [get_ports {rxn[3]}]
set_property PACKAGE_PIN N4 [get_ports {txp[3]}]
set_property PACKAGE_PIN N3 [get_ports {txn[3]}]
set_property PACKAGE_PIN K2 [get_ports {rxp[4]}]
set_property PACKAGE_PIN K1 [get_ports {rxn[4]}]
set_property PACKAGE_PIN L4 [get_ports {txp[4]}]
set_property PACKAGE_PIN L3 [get_ports {txn[4]}]
set_property PACKAGE_PIN H2 [get_ports {rxp[5]}]
set_property PACKAGE_PIN H1 [get_ports {rxn[5]}]
set_property PACKAGE_PIN J4 [get_ports {txp[5]}]
set_property PACKAGE_PIN J3 [get_ports {txn[5]}]
set_property PACKAGE_PIN F2 [get_ports {rxp[6]}]
set_property PACKAGE_PIN F1 [get_ports {rxn[6]}]
set_property PACKAGE_PIN G4 [get_ports {txp[6]}]
set_property PACKAGE_PIN G3 [get_ports {txn[6]}]

set_property PACKAGE_PIN E4 [get_ports {rxp[7]}]
set_property PACKAGE_PIN E3 [get_ports {rxn[7]}]
set_property PACKAGE_PIN F6 [get_ports {txp[7]}]
set_property PACKAGE_PIN F5 [get_ports {txn[7]}]
set_property PACKAGE_PIN D2 [get_ports {rxp[8]}]
set_property PACKAGE_PIN D1 [get_ports {rxn[8]}]
set_property PACKAGE_PIN D6 [get_ports {txp[8]}]
set_property PACKAGE_PIN D5 [get_ports {txn[8]}]
set_property PACKAGE_PIN B2 [get_ports {rxp[9]}]
set_property PACKAGE_PIN B1 [get_ports {rxn[9]}]
set_property PACKAGE_PIN C4 [get_ports {txp[9]}]
set_property PACKAGE_PIN C3 [get_ports {txn[9]}]
set_property PACKAGE_PIN A4 [get_ports {rxp[10]}]
set_property PACKAGE_PIN A3 [get_ports {rxn[10]}]
set_property PACKAGE_PIN B6 [get_ports {txp[10]}]
set_property PACKAGE_PIN B5 [get_ports {txn[10]}]


## KCU105 LEDs 
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[*]}]
set_property PACKAGE_PIN AP8 [get_ports {GPIO_LED[0]}]
set_property PACKAGE_PIN H23 [get_ports {GPIO_LED[1]}]
set_property PACKAGE_PIN P20 [get_ports {GPIO_LED[2]}]
set_property PACKAGE_PIN P21 [get_ports {GPIO_LED[3]}]
set_property PACKAGE_PIN N22 [get_ports {GPIO_LED[4]}]
set_property PACKAGE_PIN M22 [get_ports {GPIO_LED[5]}]
set_property PACKAGE_PIN R23 [get_ports {GPIO_LED[6]}]
set_property PACKAGE_PIN P23 [get_ports {GPIO_LED[7]}]

## KCU105 DIP SWITCHES
set_property IOSTANDARD LVCMOS12 [get_ports {GPIO_DIP_SW[*]}]
set_property PACKAGE_PIN AN16 [get_ports {GPIO_DIP_SW[0]}]
set_property PACKAGE_PIN AN19 [get_ports {GPIO_DIP_SW[1]}]
set_property PACKAGE_PIN AP18 [get_ports {GPIO_DIP_SW[2]}]
set_property PACKAGE_PIN AN14 [get_ports {GPIO_DIP_SW[3]}]

## KCU105 PUSH BUTTONS
set_property IOSTANDARD LVCMOS18 [get_ports GPIO_SW_N]
set_property IOSTANDARD LVCMOS18 [get_ports GPIO_SW_S]
set_property IOSTANDARD LVCMOS18 [get_ports GPIO_SW_C]
set_property IOSTANDARD LVCMOS18 [get_ports GPIO_SW_W]
set_property IOSTANDARD LVCMOS18 [get_ports GPIO_SW_E]
set_property PACKAGE_PIN AD10 [get_ports GPIO_SW_N]
set_property PACKAGE_PIN AF8 [get_ports GPIO_SW_S]
set_property PACKAGE_PIN AE10 [get_ports GPIO_SW_C]
set_property PACKAGE_PIN AF9 [get_ports GPIO_SW_W]
set_property PACKAGE_PIN AE8 [get_ports GPIO_SW_E]

## KCU105 UART
set_property IOSTANDARD LVCMOS18 [get_ports UART_RX]
set_property IOSTANDARD LVCMOS18 [get_ports UART_TX]
set_property PACKAGE_PIN K26 [get_ports UART_RX]
set_property PACKAGE_PIN G25 [get_ports UART_TX]

# 187.5 MHz
create_clock -period 5.333 -name clk_mgtref -waveform {0.000 2.667} [get_ports refclk_p]
set_property PACKAGE_PIN K5 [get_ports refclk_n]
set_property PACKAGE_PIN K6 [get_ports refclk_p]

# PL system clock:
set_property IOSTANDARD LVDS [get_ports CLK_125MHZ_P]
set_property PACKAGE_PIN G10 [get_ports CLK_125MHZ_P]
set_property PACKAGE_PIN F10 [get_ports CLK_125MHZ_N]

create_clock -period 8.000 -name CLK_125MHZ_P [get_ports CLK_125MHZ_P]

set_false_path -from [get_clocks {rxoutclk_out[2]_1}] -to [get_clocks clk_out1_clk_wiz_0]
set_false_path -from [get_clocks clk_out1_clk_wiz_0] -to [get_clocks {rxoutclk_out[2]_1}]
#
set_false_path -from [get_clocks tx_frame_clk] -to [get_clocks {rxoutclk_out[2]_1}]
set_false_path -from [get_clocks {rxoutclk_out[2]_1}] -to [get_clocks tx_frame_clk]
#
set_false_path -from [get_clocks tx_frame_clk] -to [get_clocks clk_out1_clk_wiz_0]
set_false_path -from [get_clocks clk_out1_clk_wiz_0] -to [get_clocks tx_frame_clk]
